// 管理员服务 —— 账号维护、密码校验、首个账号自举
// 安全要点：bcrypt 哈希、登录失败提示统一（防账号枚举）、超管不可删除或降权
import { BadRequestException, Injectable, Logger, NotFoundException } from '@nestjs/common'
import { InjectRepository } from '@nestjs/typeorm'
import { Like, Repository } from 'typeorm'
import { compare, hash } from 'bcryptjs'
import { ADMIN_SEED } from '../../config/app.config'
import { resolvePaging, type PageResult } from '../../common/pagination'
import { Admin } from './admin.entity'
import type {
  CreateAdminDto,
  UpdateAdminDto,
} from './dto/admin.dto'

/** bcrypt 代价因子，与会员侧保持一致 */
const BCRYPT_ROUNDS = 10

/** 每页条数默认值与上限，与其余后台列表一致 */
const DEFAULT_PAGE_SIZE = 10
const MAX_PAGE_SIZE = 100

/** 后台管理员列表查询条件 */
export interface AdminListQuery {
  keyword?: string
  page?: number
  pageSize?: number
}

/**
 * 当前 Unix 秒
 * 与 JWT 载荷的时间单位一致：JWT 的 iat/exp 都是秒，用毫秒会让两者不可比
 */
function nowInSeconds(): number {
  return Math.floor(Date.now() / 1000)
}

@Injectable()
export class AdminService {
  private readonly logger = new Logger(AdminService.name)

  constructor(
    @InjectRepository(Admin)
    private readonly repo: Repository<Admin>,
  ) {}

  /**
   * 确保存在首个超级管理员
   * 仅在表为空时创建，已有账号则不做任何事（幂等，可安全重复调用）
   */
  async ensureSeedAdmin(): Promise<void> {
    const count = await this.repo.count()
    if (count > 0) return

    await this.repo.save(
      this.repo.create({
        account: ADMIN_SEED.account,
        name: '超级管理员',
        passwordHash: await hash(ADMIN_SEED.password, BCRYPT_ROUNDS),
        perms: '[]',
        isSuper: true,
        wechatBound: false,
      }),
    )
    // 自动生成的口令只存在于本次进程内存里，不打出来就没人知道它是什么。
    // 这是唯一一次能取到它的机会，故用 warn 级别确保不被日志级别过滤掉。
    // 已显式配置 ADMIN_SEED_PASSWORD 时不回显——那份值部署方本来就有，
    // 打进日志只是多一处泄露点
    if (ADMIN_SEED.passwordAutoGenerated) {
      this.logger.warn(
        `已创建初始管理员账号「${ADMIN_SEED.account}」，本次随机初始密码为：${ADMIN_SEED.password}\n` +
          '此密码仅在本条日志中出现，请立即登录并修改。若需自定义初始密码，改用 ADMIN_SEED_PASSWORD 环境变量。',
      )
    } else {
      this.logger.warn(
        `已创建初始管理员账号「${ADMIN_SEED.account}」，初始密码取自 ADMIN_SEED_PASSWORD，请登录后立即修改`,
      )
    }
  }

  /** 按账号查找，登录用 */
  findByAccount(account: string): Promise<Admin | null> {
    return this.repo.findOne({ where: { account } })
  }

  /** 按 id 查找；不存在抛 404 */
  async findById(id: number): Promise<Admin> {
    const found = await this.repo.findOne({ where: { id } })
    if (!found) throw new NotFoundException('管理员不存在')
    return found
  }

  /**
   * 后台列表，支持账号或名称模糊匹配
   * 分页在服务端完成：账号数量虽通常不大，但不设上限意味着条数随时间只增不减
   * @param query 关键字与分页参数
   */
  async list(query: AdminListQuery = {}): Promise<PageResult<Admin>> {
    const keyword = query.keyword?.trim()
    const where = keyword
      ? [{ account: Like(`%${keyword}%`) }, { name: Like(`%${keyword}%`) }]
      : undefined

    const { page, pageSize, skip } = resolvePaging(query.page, query.pageSize, {
      defaultSize: DEFAULT_PAGE_SIZE,
      maxSize: MAX_PAGE_SIZE,
    })

    const [list, total] = await this.repo.findAndCount({
      where,
      order: { createdAt: 'DESC' },
      skip,
      take: pageSize,
    })
    return { list, total, page, pageSize }
  }

  /** 新增管理员；账号重复时报错 */
  async create(dto: CreateAdminDto): Promise<Admin> {
    const exists = await this.repo.findOne({ where: { account: dto.account } })
    if (exists) throw new BadRequestException('该账号已存在')

    return this.repo.save(
      this.repo.create({
        account: dto.account,
        name: dto.name,
        passwordHash: await hash(dto.password, BCRYPT_ROUNDS),
        perms: JSON.stringify(dto.perms ?? []),
        isSuper: false,
        wechatBound: dto.wechatBound ?? false,
      }),
    )
  }

  /** 更新管理员资料与权限；超管的权限清单不参与保存（其权限由 isSuper 表达） */
  async update(id: number, dto: UpdateAdminDto): Promise<Admin> {
    const admin = await this.findById(id)
    if (dto.name !== undefined) admin.name = dto.name
    if (dto.wechatBound !== undefined) admin.wechatBound = dto.wechatBound
    if (dto.perms !== undefined && !admin.isSuper) {
      admin.perms = JSON.stringify(dto.perms)
    }
    return this.repo.save(admin)
  }

  /** 重置指定管理员密码 */
  async resetPassword(id: number, password: string): Promise<void> {
    const admin = await this.findById(id)
    admin.passwordHash = await hash(password, BCRYPT_ROUNDS)
    // 必须一并前移：超管替「账号疑似泄露」的同事重置密码，本意就是把人踢下线，
    // 这里漏置的话密码改了而对方的会话还在，比自助改密漏置更严重
    admin.pwdChangedAt = nowInSeconds()
    await this.repo.save(admin)
  }

  /**
   * 修改自己的密码
   * @returns 原密码错误时返回提示，成功返回 null
   */
  async changeOwnPassword(id: number, oldPassword: string, newPassword: string): Promise<string | null> {
    const admin = await this.findById(id)
    const matched = await compare(oldPassword, admin.passwordHash)
    if (!matched) return '原密码错误'
    admin.passwordHash = await hash(newPassword, BCRYPT_ROUNDS)
    // 前移后，本次改密之前签发的全部令牌（含当前这条请求用的）立即失效，
    // 故前端改密成功后必须重新登录
    admin.pwdChangedAt = nowInSeconds()
    await this.repo.save(admin)
    return null
  }

  /** 删除管理员；超管不可删除，避免把自己锁在系统外 */
  async remove(id: number): Promise<void> {
    const admin = await this.findById(id)
    if (admin.isSuper) throw new BadRequestException('超级管理员不可删除')
    await this.repo.remove(admin)
  }

  /** 校验账号密码；返回 null 表示凭证无效（不区分账号不存在与密码错误） */
  async verifyCredentials(account: string, password: string): Promise<Admin | null> {
    const admin = await this.findByAccount(account)
    if (!admin) return null
    const matched = await compare(password, admin.passwordHash)
    return matched ? admin : null
  }
}
