// 运行时配置 —— 收敛 process.env 读取，业务代码只依赖此模块
// 与前端 admin/src/config、web/src/config 的分层思路一致
import { randomBytes } from 'node:crypto'

/** 解析正整数，非法值回退默认 */
function toInt(value: string | undefined, fallback: number): number {
  const num = Number(value)
  return Number.isInteger(num) && num > 0 ? num : fallback
}

/** 解析布尔，仅字符串 'true' 视为真 */
function toBool(value: string | undefined, fallback: boolean): boolean {
  if (value === undefined || value === '') return fallback
  return value === 'true'
}

/** 服务监听端口 */
export const PORT = toInt(process.env.PORT, 3000)

/** 数据库类型 */
export const DB_TYPE = (process.env.DB_TYPE || 'sqlite').trim() as 'sqlite' | 'mysql'

/** SQLite 数据文件路径 */
export const DB_SQLITE_PATH = (process.env.DB_SQLITE_PATH || 'data/website.sqlite').trim()

/**
 * 是否自动同步表结构
 * 默认 false：synchronize 会按实体差异改线上表，删列即丢数据，
 * 默认值必须是安全的那一侧。建表与表结构变更一律走迁移（含全新库），
 * 正式环境置 true 会被启动自检拒绝
 */
export const DB_SYNCHRONIZE = toBool(process.env.DB_SYNCHRONIZE, false)

/** MySQL 连接参数（DB_TYPE=mysql 时生效） */
export const MYSQL = {
  host: (process.env.DB_HOST || '127.0.0.1').trim(),
  port: toInt(process.env.DB_PORT, 3306),
  username: (process.env.DB_USERNAME || 'root').trim(),
  password: process.env.DB_PASSWORD || '',
  database: (process.env.DB_DATABASE || 'zrh_website').trim(),
}

/** 会员令牌配置 */
export const JWT_MEMBER = {
  secret: (process.env.JWT_MEMBER_SECRET || 'dev-member-secret-change-me').trim(),
  expiresIn: (process.env.JWT_MEMBER_EXPIRES_IN || '2h').trim(),
}

/** 管理员令牌配置（scope=admin，与会员令牌密钥严格分开） */
export const JWT_ADMIN = {
  secret: (process.env.JWT_ADMIN_SECRET || 'dev-admin-secret-change-me').trim(),
  expiresIn: (process.env.JWT_ADMIN_EXPIRES_IN || '8h').trim(),
}

/**
 * 正式环境启动自检：密钥沿用开发默认值、或开着 synchronize 时直接拒绝启动
 * 静默回落比启动失败危险得多——前者令牌可被伪造、表结构会被改，却没人发现。
 * 只在 NODE_ENV=production 时生效（生产镜像已固定设置），本地开发与测试不受影响
 */
function assertProductionConfig(): void {
  if (process.env.NODE_ENV !== 'production') return
  const problems: string[] = []
  const weak = (s: string) => s.length < 16 || s.startsWith('dev-')
  if (weak(JWT_MEMBER.secret)) problems.push('JWT_MEMBER_SECRET 未配置或过弱（至少 16 位）')
  if (weak(JWT_ADMIN.secret)) problems.push('JWT_ADMIN_SECRET 未配置或过弱（至少 16 位）')
  if (JWT_MEMBER.secret === JWT_ADMIN.secret) problems.push('JWT_MEMBER_SECRET 与 JWT_ADMIN_SECRET 不能相同')
  if (DB_SYNCHRONIZE) problems.push('DB_SYNCHRONIZE 在正式环境必须为 false，表结构变更走迁移')
  if (problems.length > 0) {
    throw new Error(`正式环境配置不安全，拒绝启动：\n  - ${problems.join('\n  - ')}`)
  }
}
assertProductionConfig()

/**
 * 生成一次性强随机口令
 * base64url 取 18 字节 ≈ 24 个字符，字符集无 +/= 一类在终端里易被截断的符号
 */
function randomPassword(): string {
  return randomBytes(18).toString('base64url')
}

/**
 * 初始管理员账号：仅在管理员表为空时用于创建首个账号
 *
 * 未配置 ADMIN_SEED_PASSWORD 时不再回落到固定默认口令，改为每次启动随机生成。
 * 原因：.env.example 常被直接 cp 成生产 .env，固定默认值等于把超管口令写进公开仓库。
 * 随机口令在实际创建账号时会打进启动日志（见 AdminService.ensureSuperAdmin），
 * 部署方从日志取一次即可；已有账号的部署不会用到它。
 */
const seedPasswordFromEnv = (process.env.ADMIN_SEED_PASSWORD || '').trim()
export const ADMIN_SEED = {
  account: (process.env.ADMIN_SEED_ACCOUNT || 'admin').trim(),
  password: seedPasswordFromEnv || randomPassword(),
  /** 口令是否为自动生成；决定创建账号时要不要把它打进日志 */
  passwordAutoGenerated: seedPasswordFromEnv.length === 0,
}

/**
 * 反馈到达通知配置
 * 未配置 webhook 地址即视为关闭，提交流程完全不受影响。
 * 选 webhook 而非邮件：只需一个 URL，不必在服务器上配 SMTP 账号密码，
 * 也不必为发信引入额外依赖
 */
export const FEEDBACK_NOTIFY = {
  /** 群机器人 webhook 地址，留空则不通知 */
  webhookUrl: (process.env.FEEDBACK_NOTIFY_WEBHOOK || '').trim(),
  /** 机器人类型：wecom 企业微信 / dingtalk 钉钉 / feishu 飞书，决定请求体形状 */
  type: (process.env.FEEDBACK_NOTIFY_TYPE || 'wecom').trim().toLowerCase(),
  /** 请求超时毫秒数：通知不能拖住反馈提交的响应 */
  timeoutMs: toInt(process.env.FEEDBACK_NOTIFY_TIMEOUT_MS, 3000),
}

/** 上传配置：目录、单文件大小上限、可访问的 URL 前缀 */
export const UPLOAD = {
  dir: (process.env.UPLOAD_DIR || 'data/uploads').trim(),
  maxMb: toInt(process.env.UPLOAD_MAX_MB, 2),
  /** 视频单独一档上限：视频体积与图片不在一个量级，共用一个值会把图片口子开得过大 */
  videoMaxMb: toInt(process.env.UPLOAD_VIDEO_MAX_MB, 100),
  urlPrefix: '/uploads',
  /** 允许的图片 MIME，与前端 UPLOAD_IMAGE_MIMES 保持一致 */
  imageMimes: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'] as const,
  /** MIME 对应落盘扩展名：不沿用客户端文件名，避免伪造扩展名 */
  imageExts: {
    'image/jpeg': '.jpg',
    'image/png': '.png',
    'image/webp': '.webp',
    'image/gif': '.gif',
  } as Record<string, string>,
  /**
   * 允许的视频 MIME，与前端 UPLOAD_VIDEO_MIMES 保持一致
   * 只收浏览器能直接用 <video> 播的容器格式，不收需转码的 avi/mov/wmv
   */
  videoMimes: ['video/mp4', 'video/webm', 'video/ogg'] as const,
  videoExts: {
    'video/mp4': '.mp4',
    'video/webm': '.webm',
    'video/ogg': '.ogv',
  } as Record<string, string>,
}

/**
 * AI 生图配置：封面图「AI 生成」标签页调用 OpenAI 兼容的 /v1/images/generations
 * 密钥只在服务端读取、不下发前端；apiKey 为空即视为未启用，接口返回明确提示
 */
export const AI_IMAGE = {
  baseUrl: (process.env.AI_IMAGE_BASE_URL || 'https://api.openai.com/v1').trim().replace(/\/+$/, ''),
  model: (process.env.AI_IMAGE_MODEL || 'gpt-image-1').trim(),
  apiKey: (process.env.AI_IMAGE_API_KEY || '').trim(),
  /** 单次请求超时毫秒数：生图常见耗时 10-60 秒，留足余量 */
  timeoutMs: toInt(process.env.AI_IMAGE_TIMEOUT_MS, 90_000),
  /** 每次生成的候选张数，同时即费用倍数 */
  count: toInt(process.env.AI_IMAGE_COUNT, 5),
  /** 生图尺寸，封面统一用横图 */
  size: (process.env.AI_IMAGE_SIZE || '1536x1024').trim(),
  /** 描述文本最大长度 */
  promptMaxLen: 50,
  /** 候选图在内存里的保留时长，过期未应用即丢弃 */
  candidateTtlMs: 30 * 60 * 1000,
  /** 候选缓存总条数上限，防止反复生成撑爆内存 */
  candidateMax: 60,
}

/**
 * Redis 配置 —— 短信验证码与图形验证码的共享存储
 *
 * 留空 REDIS_URL 即不启用，回落到进程内存实现：
 * 本地开发与单实例部署无须为此多起一个服务。但内存实现有两处硬伤——
 * 重启即丢（用户刚收到的验证码突然失效）、多实例下各进程各存一份
 * （发码落在 A 实例、校验打到 B 实例就必然失败），故多实例部署必须配。
 */
export const REDIS = {
  /** 连接地址，形如 redis://:password@host:6379/0；留空即用内存实现 */
  url: (process.env.REDIS_URL || '').trim(),
  /** 键名前缀，避免与同一实例上其他应用的键冲突 */
  keyPrefix: (process.env.REDIS_KEY_PREFIX || 'zrh:').trim(),
  /**
   * 单条命令超时毫秒数
   * 必须有上限：Redis 假死时 ioredis 默认会把命令一直排队，
   * 登录请求会挂到网关超时，比直接报错难排查得多
   */
  commandTimeoutMs: toInt(process.env.REDIS_COMMAND_TIMEOUT_MS, 2000),
}

/** 限流配置 */
export const THROTTLE = {
  ttl: toInt(process.env.THROTTLE_TTL, 60),
  limit: toInt(process.env.THROTTLE_LIMIT, 60),
}

/** 跨域放行来源列表 */
export const CORS_ORIGINS = (process.env.CORS_ORIGINS || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)

/** 令牌作用域，用于隔离会员与管理员两套身份 */
export const SCOPE_MEMBER = 'member'

/** 管理员令牌作用域；与 SCOPE_MEMBER 互斥，守卫两侧都做强校验 */
export const SCOPE_ADMIN = 'admin'
