/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    ChannelFilterBar: typeof import('./components/sections/ChannelFilterBar.vue')['default']
    ChannelPage: typeof import('./components/sections/ChannelPage.vue')['default']
    ChannelPagination: typeof import('./components/sections/ChannelPagination.vue')['default']
    ContentBlock: typeof import('./components/sections/ContentBlock.vue')['default']
    DefaultLayout: typeof import('./components/layout/DefaultLayout.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./components/sections/EmptyState.vue')['default']
    ItemLink: typeof import('./components/sections/ItemLink.vue')['default']
    MemberEntry: typeof import('./components/layout/MemberEntry.vue')['default']
    MobileNav: typeof import('./components/layout/MobileNav.vue')['default']
    PageHero: typeof import('./components/sections/PageHero.vue')['default']
    PhoneIcon: typeof import('./components/layout/PhoneIcon.vue')['default']
    QuickActions: typeof import('./components/layout/QuickActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeImage: typeof import('./components/common/SafeImage.vue')['default']
    SectionHeading: typeof import('./components/sections/SectionHeading.vue')['default']
    SkeletonRows: typeof import('./components/common/SkeletonRows.vue')['default']
    Style2ContentBlock: typeof import('./components/sections/Style2ContentBlock.vue')['default']
    Style2Footer: typeof import('./components/layout/Style2Footer.vue')['default']
    Style2Header: typeof import('./components/layout/Style2Header.vue')['default']
    Style2PageHero: typeof import('./components/sections/Style2PageHero.vue')['default']
    VideoPlayer: typeof import('./components/sections/VideoPlayer.vue')['default']
  }
}
